### PR TITLE
SUR-310 - alert button type change, and select text size change

### PR DESCRIPTION
**Pull request by ravindra114**
### Description
Select Atom: Changed the select atom font size ( placeholder and options)
https://d.pr/v/aj1pmR

Select Molecule: Changed the height auto. So that it will not show any empty space. 
https://d.pr/v/ZJuF8o

Alert Atom: Changed button type to link from button in alert
https://d.pr/i/ECqtEv

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by BabuTechBsf — COMMENTED** [review]
Please add description and Pics for reference what change was made here.

**Review by jaieds — CHANGES_REQUESTED** [review]
It's working fine for the combo box but overflowing when it's a normal selector.

https://d.pr/v/3aaZSN

**Comment by ravindra114** [comment]
> Please add description and Pics for reference what change was made here.

done

**Review by jaieds — APPROVED** [review]
Resolved.

https://share.cleanshot.com/rR915GF7

**Review by BabuTechBsf — APPROVED** [review]
Pls verify the font sizes for Searchbox also , make changes if needed. To be consistent.

**Review by JelenaTakac — APPROVED** [review]

**Pull request merged**
