### PR TITLE
SUR-263 - Fix - Custom JSX in Label, and Heading/Description Logic

### PR DESCRIPTION
**Pull request by ravindra114**
### Description
You can pass JSX as label={ jsx_component }, also only heading or only description can be shown now.

### Screenshots
https://d.pr/i/Ph0bez

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by jaieds — CHANGES_REQUESTED** [review]
Fix alignment for the below cases.
1. Custom label.
2.  Entered only description.

Screenshot: https://d.pr/i/pVPyM9

**Comment by ravindra114** [comment]
> Fix alignment for the below cases.
> 
> 1. Custom label.
> 2. Entered only description.
> 
> Screenshot: https://d.pr/i/pVPyM9

Fixed for heading only or description only, for custom label it will be handled manually, here you can try "self-center"

**Comment by jaieds** [comment]
> > Fix alignment for the below cases.
> > 
> > 1. Custom label.
> > 2. Entered only description.
> > 
> > Screenshot: https://d.pr/i/pVPyM9
> 
> Fixed for heading only or description only, for custom label it will be handled manually, here you can try "self-center"

IMO, alignment also needs to be handled from the component for custom labels.

**Comment by ravindra114** [comment]
> > > Fix alignment for the below cases.
> > > 
> > > 1. Custom label.
> > > 2. Entered only description.
> > > 
> > > Screenshot: https://d.pr/i/pVPyM9
> > 
> > 
> > Fixed for heading only or description only, for custom label it will be handled manually, here you can try "self-center"
> 
> IMO, alignment also needs to be handled from the component for custom labels.

done check

**Comment by ravindra114** [comment]
> Fix alignment for the below cases.
> 
> 1. Custom label.
> 2. Entered only description.
> 
> Screenshot: https://d.pr/i/pVPyM9

check please

**Review by vrundakansara — APPROVED** [review]

**Pull request merged**
