### PR TITLE
SUR-312 - UAT feedback - Editor input space issue

### PR DESCRIPTION
**Pull request by jaieds**
### Screenshots

- https://d.pr/v/AZ5KUw

### Checklist:

-   [x] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by ravindra114 — CHANGES_REQUESTED** [review]
seems fine, have one improvement
https://d.pr/v/AHDV8E

when I did backspace once, it should not add space again.

**Review by JelenaTakac — CHANGES_REQUESTED** [review]
Please check this video: https://bsf.d.pr/v/6srNkA
You can add description and control for autoSpaceAfterMention in storybook.

**Comment by jaieds** [comment]
@ravindra114 / @JelenaTakac, Done

**Review by vrundakansara — APPROVED** [review]

**Review by JelenaTakac — APPROVED** [review]
Tested: https://bsf.d.pr/v/a97gso

**Review by BabuTechBsf — APPROVED** [review]
Add wrapperClass and extend props to root Input or root element.
Add stories for opened/search results state.
autoSpaceAfterMention can be spaceAfterMention?

**Comment by jaieds** [comment]
@BabuTechBsf,
1. Add wrapperClass and extend props to root Input or root element. ✅ `Added`
2. Add stories for opened/search results state. ⚠️ `Not possible. There's no option available to control the dropdown open state.`
3. autoSpaceAfterMention can be spaceAfterMention? ⚠️ `Keept the same name. The current name will give developers a clear idea that, if they enable this, a space will be inserted after the `mention` node automatically. Please let me know if you have any opinion on this.`

**Pull request merged**
