### PR TITLE
SUR-280 Organism: Implement Top navbar

### PR DESCRIPTION
**Pull request by JelenaTakac**
### Description

# Topbar Component Documentation

## Description

The `Topbar` is a flexible navigation bar component that provides three sections: `Left`, `Middle`, and `Right`. It allows easy alignment and placement of items within each section.

### `children`
- **Type:** `ReactNode`
- **Description:** Elements to render inside the Topbar container, typically the `Topbar.Left`, `Topbar.Middle`, and `Topbar.Right` components.

### `className`
- **Type:** `string`
- **Description:** Additional classes to customize the Topbar container's styles.

### `children`
- **Type:** `ReactNode`
- **Description:** Elements to render inside the `Topbar.Left` container, usually icons, logos, or navigation items.

### `align`
- **Type:** `string`
- **Default:** `"center"`
- **Description:** Defines how the content inside the Middle section is aligned. Options include:
  - `"left"`
  - `"center"`
  - `"right"`

### `children`
- **Type:** `ReactNode`
- **Description:** Elements to render inside the `Topbar.Middle` container, usually navigation links, buttons, or other interactive elements.

### `children`
- **Type:** `ReactNode`
- **Description:** Elements to render inside the `Topbar.Right` container, typically icons, user profile, badges, or help buttons.

### `children`
- **Type:** `ReactNode`
- **Description:** Content or components to render inside the `Topbar.Item`.

### `className`
- **Type:** `string`
- **Description:** Additional classes to customize the Item styling.

```jsx
    <Topbar>
        <Topbar.Left>
            <Topbar.Item>
                <Logo />
            </Topbar.Item>
        </Topbar.Left>

        <Topbar.Middle align="left">
            <Topbar.Item>
                <div className='flex gap-2'>
                    <div>Nav Item 1</div>
                    <div>Nav item 2</div>
                    <div>Nav Item 3</div>
                </div>
            </Topbar.Item>
            <Topbar.Item>
                <Button>Upgrade to Pro</Button>
            </Topbar.Item>
        </Topbar.Middle>

        <Topbar.Right>
            <Topbar.Item>
                <Badge  />
            </Topbar.Item>
            <Topbar.Item className='flex gap-2'>
                <CircleHelp />
                <Megaphone />
            </Topbar.Item>
            <Topbar.Item>
                <Avatar />
            </Topbar.Item>
        </Topbar.Right>
    </Topbar>
```

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

### CODE REVIEW

**Review by BabuTechBsf — CHANGES_REQUESTED** [review]
There is inconsistency in file naming, Should be Topbar/Navbar in all places instead of top-navbar. Check in all places.

**Comment by JelenaTakac** [comment]
> There is inconsistency in file naming, Should be Topbar/Navbar in all places instead of top-navbar. Check in all places. There should be some options like enable fixed/sticky postion, enable border/shadow, custom height, custom gaps etc... ? What about responsive mobile navbar?

**Comment by JelenaTakac** [comment]
> There is inconsistency in file naming, Should be Topbar/Navbar in all places instead of top-navbar. Check in all places. There should be some options like enable fixed/sticky postion, enable border/shadow, custom height, custom gaps etc... ? What about responsive mobile navbar?

Resolved inconsistency in file naming and added custom gaps.

**Review by jaieds — COMMENTED** [review]
@JelenaTakac / @BabuTechBsf, I tried to match the height of the Top Nav-bar which is `64px`, but because of the padding items inside were overflowing. Is it expected and will it create any issues in the future?

Please check the screenshot for more clarity. 

**Screenshot:** https://d.pr/i/TibBQU

**Comment by JelenaTakac** [comment]
> @JelenaTakac / @BabuTechBsf, I tried to match the height of the Top Nav-bar which is `64px`, but because of the padding items inside were overflowing. Is it expected and will it create any issues in the future?
> 
> Please check the screenshot for more clarity.
> 
> **Screenshot:** https://d.pr/i/TibBQU

@jaieds, I connected with @BabuTechBsf regarding this issue. We decided to set the min-height to 64px, but the overall height will depend on the inner components like Button, Avatar, Badge, etc.

**Comment by jaieds** [comment]
> > @JelenaTakac / @BabuTechBsf, I tried to match the height of the Top Nav-bar which is `64px`, but because of the padding items inside were overflowing. Is it expected and will it create any issues in the future?
> > Please check the screenshot for more clarity.
> > **Screenshot:** https://d.pr/i/TibBQU
> 
> @jaieds, I connected with @BabuTechBsf regarding this issue. We decided to set the min-height to 64px, but the overall height will depend on the inner components like Button, Avatar, Badge, etc.

@JelenaTakac, If we want the Navbar exactly `64px` height how can we do that?

**Review by jaieds — APPROVED** [review]

**Review by vrundakansara — CHANGES_REQUESTED** [review]
@JelenaTakac - We will need storybook story for this too

**Review by vrundakansara — APPROVED** [review]

**Pull request merged**
