### PR TITLE
SUR-242, SUR-323 - Setup Tests for UI components

### PR DESCRIPTION
**Pull request by jaieds**
### Description

- Setup test environment.
- Added test for Button and Select Component.

- **How to Run test:**
  - Run `npm install` for the first time only.
  - Run `npm run storybook`
  - In the command/terminal run `npm run test` (bulk test). It will begin the test and will show the result.
  - To run test in watch mode run `npm run test:watch`.

#### 👉 [All about React component testing with Storybook](https://github.com/brainstormforce/force-ui/wiki/All-about-React-component-testing-with-Storybook)

**CI Setup instructions:** [Storybook Doc](https://storybook.js.org/docs/writing-tests/test-runner#set-up-ci-to-run-tests)

### Checklist:

-   [x] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [x] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

### CODE REVIEW

**Comment by vrundakansara** [comment]
@jaieds - Please write a short document about it too.

- What are tests?
- Why are they important?
- How to write tests?
- What points should one keep in mind while writing tests?

You can add the readme in this PR or write a [wiki](https://github.com/brainstormforce/force-ui/wiki/_new) for the same.

**Comment by jaieds** [comment]
@vrundakansara, I've created a wiki page 👉 [All about React component testing with Storybook](https://github.com/brainstormforce/force-ui/wiki/All-about-React-component-testing-with-Storybook)

**Comment by jaieds** [comment]
@vrundakansara, I've added CI for the Test.

**Review by vrundakansara — APPROVED** [review]
@jaieds - Shall we fix the a11y issues as well?
Or shall we do it in another PR?

**Comment by jaieds** [comment]
> @jaieds - Shall we fix the a11y issues as well? Or shall we do it in another PR?

@vrundakansara, We can fix it in another PR.

**Pull request merged**
